### ISSUE TITLE
Mutation: Prevent empty string in args

### ISSUE THREAD

**Issue by mfakhrys** [get-convex/convex-js#4]
Hello, is there any way to prevent an empty string when we call a mutation? 

In my case, I have a users table, and in the "create" mutation I accept "name" args, currently empty string is accepted.

Is there any built in method? Or do I need to reject it in handler? 

Thanks in advance

**Comment by xixixao** [comment]
Hey @mfakhrys, you can reject the invalid value in the handler. This gives you the power to enforce any rule you'd like, arbitrarily complex (you have a whole Turing-complete language at your disposal).

We might consider more granular validators in the future.
