### ISSUE TITLE
[Suggestion] Don't Delete convex.json When Running npx convex dev

### ISSUE THREAD

**Issue by Luzefiru** [get-convex/convex-js#6]
# Background Information

I'm developing a project within a team wherein our React client consumes the Convex API. As of the moment, the onboarding process and development environment setup is quite cumbersome due to unintended(?) actions caused by `npx convex dev`.

We have a `client/convex.json` file that specifies the following information that is crucial to the functionality of the client side:

```json
{
    "functions": "./src/_convex"
}
```

Running `npx convex dev` and going through the setup wizard deletes this file and then results in a ```[CONVEX Q(files:getFilesByDocumentId)] Could not find public function for 'files:getFilesByDocumentId'. Did you forget to run `npx convex dev` or `npx convex deploy`?``` error.

## Demo
![demo](https://github.com/get-convex/convex-js/assets/105530193/d7e4bb93-44df-4719-976a-bf239349241e)

# The Suggestion

If it's possible, `npx convex dev` shouldn't delete these configuration files on directories without `.env.local`'s Convex files. Or perhaps, the wizard can ask questions if there is an existing configuration files or if there are files to ignore during the initialization process.

Also, an `npx convex dev --verbose` flag would be nice to see explicit updates on any file changes.

**Comment by xixixao** [comment]
@Luzefiru that sounds like a bug. We'll look into it. Meanwhile make sure you are on the latest version of convex, as the issue might have already been fixed.

**Comment by thomasballinger** [comment]
I think this was fixed a while ago, testing with 1.13.1 it is no longer an issue.
